# 端口配置
server.port=8081

# 数据库连接地址（改成 localhost！）
spring.datasource.url=jdbc:mysql://localhost:3306/fitness_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8

# 数据库用户名和密码
spring.datasource.username=root
spring.datasource.password=chenxu0517A!

# JPA 配置
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true